#### general settings
name: beta_0510_blur0040_noise0050 # remove the "debug" for normal training
use_tb_logger: true
model: sr
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT_cond
    cond_norm: [40, 50]
#    cond_norm: [40, 50, 92]  # for 3D modulation
    dataroot_GT: ../datasets/DIV2K_sub
    #### 2D ####
    dataroot_LQ: ../datasets/DIV2K_beta_0510_2group_k04_noise0050_41x51 
    #### 3D ####
    # dataroot_LQ: ../datasets/DIV2K_3group_beta0510_k04_noise0050_q0010_41x51x47 

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 64 # crop size
    use_flip: true
    use_rot: true
    color: RGB

####################### 
#### 2D validation #### 
####################### 
  val0:
    name: blur0_noise0
    mode: LQGT_cond
    cond_norm: [40, 50]
    dataroot_GT: ../datasets/val/blur0_noise0
    dataroot_LQ: ../datasets/val/blur0_noise0

  val1:
    name: blur0_noise15
    mode: LQGT_cond
    cond_norm: [40, 50]
    dataroot_GT: ../datasets/val/blur0_noise0
    dataroot_LQ: ../datasets/val/blur0_noise15

  val2:
    name: blur0_noise50
    mode: LQGT_cond
    cond_norm: [40, 50]
    dataroot_GT: ../datasets/val/blur0_noise0
    dataroot_LQ: ../datasets/val/blur0_noise50

  val3:
    name: blur10_noise0
    mode: LQGT_cond
    cond_norm: [40, 50]
    dataroot_GT: ../datasets/val/blur0_noise0
    dataroot_LQ: ../datasets/val/blur10_noise0

  val4:
    name: blur40_noise0
    mode: LQGT_cond
    cond_norm: [40, 50]
    dataroot_GT: ../datasets/val/blur0_noise0
    dataroot_LQ: ../datasets/val/blur40_noise0

  val5:
    name: blur10_noise15
    mode: LQGT_cond
    cond_norm: [40, 50]
    dataroot_GT: ../datasets/val/blur0_noise0
    dataroot_LQ: ../datasets/val/blur10_noise15

  val6:
    name: blur40_noise50
    mode: LQGT_cond
    cond_norm: [40, 50]
    dataroot_GT: ../datasets/val/blur0_noise0
    dataroot_LQ: ../datasets/val/blur40_noise50

####################### 
#### 3D validation #### 
####################### 
#   val0:
#     name: blur0_noise0_jpeg102
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur0_noise0_jpeg102
#
#   val1:
#     name: blur0_noise0_jpeg80
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur0_noise0_jpeg80
#
#   val2:
#     name: blur0_noise0_jpeg10
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur0_noise0_jpeg10
#
#   val3:
#     name: blur0_noise15_jpeg102
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur0_noise15_jpeg102
#
#   val4:
#     name: blur0_noise50_jpeg102
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur0_noise50_jpeg102
#
#   val5:
#     name: blur10_noise0_jpeg102
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur10_noise0_jpeg102
#
#   val6:
#     name: blur40_noise0_jpeg102
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur40_noise0_jpeg102
#
#   val7:
#     name: blur10_noise15_jpeg80
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur10_noise15_jpeg80
#
#   val8:
#     name: blur40_noise50_jpeg10
#     mode: LQGT_cond
#     cond_norm: [40, 50, 92]
#     dataroot_GT: ../datasets/val/blur0_noise0_jpeg102
#     dataroot_LQ: ../datasets/val/blur40_noise50_jpeg10

#### network structures
network_G:
  which_model_G: CResMDNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 32
  cond_dim: 2 # modulation dimension 2 | 3

#### path
path:
  pretrain_model_G: ~ # None(~) for basic model; path of basic model for adafm training
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 5e-4
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR

  niter: 1000000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000, 800000]  # [500000] for basic model, [1000000] for adafm-net
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
